---
title: "Analysis of Maize, Nitrogen and Tillage experiment"
author: "Deependra Dhakal"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    toc: yes
    toc_depth: 3
    keep_tex: yes
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
- \usepackage{xcolor}
- \usepackage{rotating}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{subfig}
- \usepackage[format=hang,labelfont=bf,margin=0.5cm,justification=centering]{caption}
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
knitr::opts_chunk$set(tidy = TRUE, cache = TRUE, 
                      echo = FALSE, 
                      tidy.opts = list(width.cutoff=50), 
                      eval = TRUE, warning = FALSE, message = FALSE,
                      # fig.show = "hold", 
                      fig.align = "center", fig.width = 5,
                      fig.asp = 0.9, out.width = "0.7\\linewidth")
options(knitr.kable.NA = "", digits = 3)
# require(lmerTest)
require(agricolae)
```


```{r load-data}
two_fac_maize <- readxl::read_xlsx("./data.xlsx", sheet = "maize_traits") %>% 
  mutate_at(vars(`plot no`, `replication`, Tillage, Nitrogen), as.factor)

two_fac_maize_soil <- readxl::read_xlsx("./data.xlsx", sheet = "maize_tr_partial") %>% 
  mutate_at(vars(`plot no`, `replication`, Tillage, Nitrogen), as.factor)
```


# Analysis of 2 factorial RCBD

Since you have 3 levels for one factor and 3 levels for the other, data from an RCBD with 3 replications would be analysed as follows:

```{r design-and-book, results='asis'}
set.seed(9845333)

two_fac_maize <- two_fac_maize %>%
  mutate(`Tillage` = fct_recode(`Tillage`, 
                                Tillage1 = "1", 
                                Tillage2 = "2"), 
         Nitrogen = fct_recode(Nitrogen, 
                               Nitrogen1 = "1", 
                               Nitrogen2 = "2",
                               Nitrogen3 = "3",
                               Nitrogen4 = "4",
                               Nitrogen5 = "5")) %>% 
  rename_all(function(x)stringr::str_replace_all(x, "\ ", "_"))

two_fac_maize_soil <- two_fac_maize_soil %>%
  mutate(`Tillage` = fct_recode(`Tillage`, 
                                Tillage1 = "1", 
                                Tillage2 = "2"), 
         Nitrogen = fct_recode(Nitrogen, 
                               Nitrogen1 = "1", 
                               Nitrogen2 = "2",
                               Nitrogen3 = "3",
                               Nitrogen4 = "4",
                               Nitrogen5 = "5")) %>% 
  rename_all(function(x)stringr::str_replace_all(x, "\ ", "_"))

knitr::kable(two_fac_maize[c(1:4)], 
             format = "latex", 
             caption = "Design field book of a two factorial RCBD experiment", 
             digits = 3, booktabs = TRUE,
             col.names = c("Block", "Fruit thinning", 
                           "Defoliation", "Days for flowering"), 
             align = 'l') %>% 
  kableExtra::kable_styling(latex_options = c("striped", 
                                              "hold_position", "scale_down"), 
                            full_width = TRUE, font_size = 11, position = "left")
```


# Analyis

```{r analysis-and-results}

# rcbd model
two_fac_model <- map(c("Plant_ht65", "plant_ht135", "Plant_ht160", 
                       "LAI65", "LAI135", "LAI160", "Tassling", 
                       "sliking", "Grn_lenth", "cob_lenth", 
                       "Test_wt", "yield", "straw_yld", 
                       "HI", "NOR/Cob", "NOK/COB", "plant(n)", "seed(N)"),
                     .f = ~ lm(get(.x) ~ Nitrogen*Tillage + 
                                 replication/Nitrogen, 
                               data = two_fac_maize))

two_fac_model_soil <- map(c("plant(n)", 
                            "OM", "nitrogen", "phosp", 
                            "potas", "ph", "seed(N)", "yield", 
                            "nutrient_up", "nup"),
                          .f = ~ lm(get(.x) ~ Nitrogen*Tillage + 
                                      replication/Nitrogen, 
                                    data = two_fac_maize_soil))

# mean separation
map_inner <- function(y)map_dfr(list("Nitrogen", "Tillage", 
                                     c("Nitrogen", "Tillage")), 
                  function(x)agricolae::duncan.test(y, trt = x) %>% pluck("groups") %>% 
                    rownames_to_column("Treatment"))

two_fac_gmeans <- map(two_fac_model, map_inner)
two_fac_gmeans <- map(.x = two_fac_gmeans,
                      .f = ~ .x %>% rename("Mean"="get(.x)"))

two_fac_gmeans_soil <- map(two_fac_model_soil, map_inner)
two_fac_gmeans_soil <- map(.x = two_fac_gmeans_soil,
                      .f = ~ .x %>% rename("Mean"="get(.x)"))

numeric_trait_names <- two_fac_maize %>% map_lgl(is.numeric) %>% which() %>% names()
numeric_trait_names_soil <- two_fac_maize_soil %>% map_lgl(is.numeric) %>% which() %>% names()

two_fac_gmeans_df <- two_fac_gmeans %>% 
  purrr::reduce(left_join, by = "Treatment") %>% 
  magrittr::set_colnames(c("Treatment", paste(rep(numeric_trait_names, each = 2), c("", "group"))))

two_fac_gmeans_df_soil <- two_fac_gmeans_soil %>% 
  purrr::reduce(left_join, by = "Treatment") %>% 
  magrittr::set_colnames(c("Treatment", paste(rep(numeric_trait_names_soil, each = 2), c("", "group"))))
  
# cvs of all traits
two_fac_cvs <- data.frame(trait = numeric_trait_names, 
                          cv = two_fac_model %>% 
                            map_dbl(agricolae::cv.model))

two_fac_cvs_soil <- data.frame(trait = numeric_trait_names_soil, 
                          cv = two_fac_model_soil %>% 
                            map_dbl(agricolae::cv.model))

# # set contrasts for comparing treatment means
contrasts(two_fac_maize$Fruit_thinning)[two_fac_maize$Fruit_thinning %>% as.numeric(), ,drop = FALSE]
# the divisor should best be equal to (number of reps*number of treatment factor levels)
divisor <- length(levels(two_fac_maize$Rep))*length(levels(two_fac_maize$Fruit_thinning))
# the contrast.obj should have be a matrix with colMeans==0 for all possible set of contrasts
se.contrast(aov(two_fac_model[[3]]), contrast.obj = 
              contrasts(two_fac_maize$Fruit_thinning)[two_fac_maize$Fruit_thinning, , drop = FALSE]/divisor)

# # write model cvs to csv
# two_fac_cvs %>% write_csv(path = "cv_results.csv")
# two_fac_cvs_soil %>% write_csv(path = "cv_results_soil.csv")

# write a single file to csv
two_fac_gmeans_df %>%
  write_csv(path = "dmrt_means_result.csv",
            na = "")

two_fac_gmeans_df_soil %>%
  write_csv(path = "dmrt_means_result_soil.csv",
            na = "")

# # write individual files to csv
# dmrt_files <- two_fac_maize %>% 
#   map_lgl(is.numeric) %>% 
#   which() %>% 
#   names() %>% 
#   stringr::str_replace_all("/", "_") # filename contains "\", to fix the error
# ifelse(dir.exists("./dmrt_results/"), 
#        "The directory already exists", 
#        dir.create("./dmrt_results/"))
# 
# walk2(two_fac_gmeans, paste("./dmrt_results/", dmrt_files, ".csv", sep = ""), 
#       .f = ~ write_csv(.x, .y))

# zip all files
# dmrt_dir_file_paths <- dir("./dmrt_results/", full.names = TRUE)
# zip(zipfile = "dmrt_all_traits.zip", files = dmrt_dir_file_paths)

# for other tests
# agricolae::SNK.test(ramesh_rcbd_2fac, "Fruit_thinning", console = TRUE)
# agricolae::HSD.test(ramesh_rcbd_2fac, "Fruit_thinning", console = TRUE)
# save.image("maize_88_responses")
```


```{r two-factor-model-summary, results='asis', eval=FALSE}
# # must use this function with float=FALSE in stargazer
long_stargazer <- function(...){
  output <- capture.output(stargazer::stargazer(...))
  # The lines 4 and second last lines are the ones we want to remove...
  output[c(4, length(output)-1)] <- output[c(4, length(output)-1)] %>% 
    stringr::str_replace("tabular", "longtable")
  # cat out the results - this is essentially just what stargazer does too
  cat(paste(output, collapse = "\n"), "\n")
}

long_stargazer(two_fac_model,
               title = "Mean comparison of Post-harvest traits", 
               style = "all", digits = 2, 
               header = FALSE, font.size = "small", 
               column.labels = c("\\parbox[t]{2.0cm}{Days for Flowering}", 
                                 "\\parbox[t]{2.0cm}{Days for Fruit Set}",
                                 "\\parbox[t]{2.0cm}{Days for fruit set to Harvest}", 
                                 "\\parbox[t]{2.0cm}{Firmness}",
                                 "\\parbox[t]{2.0cm}{pulp weight}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 3 DAH}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 5 DAH}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 7 DAH}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 9 DAH}", 
                                 "\\parbox[t]{2.0cm}{TSS}"), 
               model.names = TRUE, dep.var.labels.include = FALSE, 
               digits.extra = 3, align = TRUE, single.row = TRUE, 
               float.env = "table*",
               df = FALSE, omit.stat = c("adj.rsq"),
               column.sep.width = "1pt", float = TRUE)
```


```{r two-fac-anova, results='asis', eval=FALSE}
walk(two_fac_model, ~ stargazer::stargazer(anova(.x), header = FALSE,
                                           # float = TRUE, float.env = "table*",
                                           font.size = "small", digits.extra = 3,
                                           align = TRUE))

two_fac_tanova <- map(two_fac_model, ~ anova(.x) %>% broom::tidy())
two_fac_tanova_soil <- map(two_fac_model_soil, ~ anova(.x) %>% broom::tidy())

# # write a single file to csv
# walk2(.x = two_fac_tanova,
#       .y = numeric_trait_names,
#       .f = ~.x %>% add_row() %>% add_column(.before = 1,
#                                             Trait = c(.y, rep(NA, times = (nrow(.)-1)))) %>%
#         write_csv(path = "anova_test_results.csv",
#                   # row.names = FALSE,
#                   na = "", append = TRUE, col_names = TRUE))

# # write a single file to csv
# walk2(.x = two_fac_tanova_soil,
#       .y = numeric_trait_names_soil,
#       .f = ~.x %>% add_row() %>% add_column(.before = 1,
#                                             Trait = c(.y, rep(NA, times = (nrow(.)-1)))) %>%
#         write_csv(path = "anova_test_results_soil.csv",
#                   # row.names = FALSE,
#                   na = "", append = TRUE, col_names = TRUE))

# # write individual files to csv
# ifelse(dir.exists("./anova_results/"), 
#        "The directory already exists", 
#        dir.create("./anova_results/"))
# 
# walk2(two_fac_tanova, paste("./anova_results/", dmrt_files, ".csv", sep = ""), # "dmrt_files" is just filenames
#       .f = ~ write_csv(.x, .y, na = ""))

# zip all files
# anova_dir_file_paths <- dir("./anova_results/", full.names = TRUE)
# zip(zipfile = "anova_all_traits.zip", files = anova_dir_file_paths)
```


# All results summary

```{r two-fac-groups-tab, results='asis'}

walk2(.x = two_fac_gmeans, 
      .y = c("Days_for_Flowering", 
             "Days_for_Fruit_Set", "Days_for_fruit_set_to_Harvest", "Firmness", 
             "pulp_weight", "PWL%_3DAH", "PWL%_5_DAH", "PWL%_7_DAH", "PWL%_9_DAH", 
             "TSS", "Abortion_%", "Fruit_set_%", "Total_no_of_flowers", "Total_fruit_set", 
             "Ht_30_DAT", "Ht_60_DAT", "Ht_90_DAT", "Ht_120_DAT", "Ht_150_DAT", 
             "Ht_180_DAT", "Ht_270_DAT", "NoL_30_DAT", "NoL_60_DAT", "NoL_90_DAT", 
             "NoL_120_DAT", "NoL_150_DAT", "NoL_180_DAT", "NoL_270_DAT", "SD_90_DAT", 
             "SD_120_DAT", "SD_150_DAT", "SD_180_DAT", "SD_270_DAT", "PL_30_DAT", 
             "PL_60_DAT", "PL_90_DAT", "PL_120_DAT", "PL_150_DAT", "PL_180_DAT", 
             "LA_30_DAT", "LA_60_DAT", "LA_90_DAT", "LA_120_DAT", "LA_150_DAT", 
             "NoF_100_DAT", "NoF_107_DAT", "NoF_114_DAT", "NoF_121_DAT", "NoF_128_DAT", 
             "NoF_135_DAT", "NoF_142_DAT", "NoF_149_DAT", "NoF_156_DAT", "NoF163_DAT", 
             "NoF_170_DAT", "NoFrtS_140_DAT", "NoFrtS_147_DAT", "NoFrtS_154_DAT", 
             "NoFrtS_161_DAT", "NoFrtS_168_DAT", "NoFrtS_175_DAT", "NoFrtS_182_DAT", 
             "NoFrtS_190_DAT", "NoAFF_120_DAT", "NoAFF_127_DAT", "NoAFF_134_DAT", 
             "NoAFF_141_DAT", "NoAFF_148_DAT", "NoAFF_155_DAT", "NoAFF_162_DAT", 
             "Total_abortion_250_DAT", "TSS__1", "TA", "TSS/TA_Ratio", "PH", 
             "Vitamin_C", "PWL%_3DAH__1", "PWL%_5_DAH__1", "PWL%_7_DAH__1", 
             "PWL%_9_DAH__1", "fungal_severity", "length_(cm)", "diameter_(cm)", 
             "seed_weight", "Peel_weight", "yield_(in_kg)", "Weight_(g)_Of_fruit", 
             "pulp_weight__1") %>% 
        stringr::str_replace_all("_", "\ ") %>% 
        stringr::str_replace_all("%", "\\\\%"),
      .f = ~ knitr::kable(.x, 
                          caption = paste("Treatment means with groups of", .y),
                          format = "latex", longtable = TRUE,
                          digits = 2, booktabs = TRUE, 
                          align = 'l', escape = TRUE) %>% 
        kableExtra::kable_styling(latex_options = c("striped", 
                                                    "hold_position"), 
                                  font_size = 12, position = "left") %>% 
        print())
```

# Correlation matrix of numeric variables

```{r correlation-annotate}
# This function annotates the correlation coefficients 
# with the stars corresponding to the level of significance
# x is a matrix containing the data
# method : correlation method. "pearson"" or "spearman"" is supported
# removeTriangle : remove upper or lower triangle
# results : "html" or "latex" (default)
# align: a vector of alignment values as is specified in xtable(x, align)

large <- function(x){
  paste0('{\\footnotesize{\\bfseries ', x, '}}')
}

corstars <-function(x, align, caption, method=c("pearson", "spearman"), removeTriangle=c("upper", "lower"),
                    result=c("none", "html", "latex")){
  #Compute correlation matrix
  require(Hmisc)
  x <- as.matrix(x)
  correlation_matrix<-rcorr(x, type=method[1])
  R <- correlation_matrix$r # Matrix of correlation coeficients
  p <- correlation_matrix$P # Matrix of p-value 
  
  ## Define notions for significance levels; spacing is important.
  mystars <- ifelse(p < .0001, "****", ifelse(p < .001, "*** ", ifelse(p < .01, "**  ", ifelse(p < .05, "*   ", "    "))))
  
  ## trunctuate the correlation matrix to two decimal
  R <- format(round(cbind(rep(-1.11, ncol(x)), R), 2))[,-1]
  
  ## build a new matrix that includes the correlations with their apropriate stars
  Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x))
  diag(Rnew) <- paste(diag(R), " ", sep="")
  rownames(Rnew) <- colnames(x)
  colnames(Rnew) <- paste(colnames(x), "", sep="")
  
  ## remove upper triangle of correlation matrix
  if(removeTriangle[1]=="upper"){
    Rnew <- as.matrix(Rnew)
    Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
  }
  
  ## remove lower triangle of correlation matrix
  else if(removeTriangle[1]=="lower"){
    Rnew <- as.matrix(Rnew)
    Rnew[lower.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
  }
  
  ## remove last column and return the correlation matrix
  Rnew <- cbind(Rnew[1:length(Rnew)-1])
  if (result[1]=="none") return(Rnew)
  else{
    if(result[1]=="html") print(xtable(Rnew), type="html", comment = FALSE)
    else print(xtable(Rnew, auto = TRUE,  align = align, caption = caption), type="latex", 
               comment = FALSE, size = "\\footnotesize", 
               sanitize.colnames.function = large, 
               booktabs = TRUE, tabular.environment="longtable", 
               floating=FALSE)
  }
} 
```


```{r correlation-postharvest, results='asis'}
# crop yield and agro-morphology
cortable <- corstars(two_fac_maize %>% 
                       select_at(which(map_lgl(., is.numeric))))
# # write to csv
# cortable %>% rownames_to_column(var = "traits") %>% write_csv("correlation_maize_results.csv")

# # html
# cortable %>%
#   knitr::kable(format = "html",
#                caption = "Pearson correlation coefficients of Post harvest traits",
#                booktabs = TRUE, align = "l"
#                # longtable = TRUE
#                ) %>%
#   kableExtra::kable_styling(font_size = 14, bootstrap_options = c("striped", "responsive")) %>%
#   # kableExtra::column_spec(1:11, width = "0.11\\\\textwidth") %>%
#   kableExtra::row_spec(0, bold = TRUE) %>%
#   kableExtra::column_spec(1, bold = TRUE) %>%
#   kableExtra::footnote(general = "p < .0001: **** ; p < .001: *** ; p < .01: ** ; p < .05: *",
#                        threeparttable = TRUE, escape = FALSE)

cortable %>%
  rename_all(function(x)stringr::str_trunc(x, width = 4, side = "c", ellipsis = "")) %>% 
  knitr::kable(format = "latex",
               caption = "Pearson correlation coefficients of Post harvest traits",
               booktabs = TRUE, align = "l"
               # longtable = TRUE
               ) %>%
  kableExtra::kable_styling(font_size = 14, latex_options = c("striped", "scale_down")) %>%
  # kableExtra::column_spec(1:11, width = "0.11\\\\textwidth") %>%
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::footnote(general = "p < .0001: **** ; p < .001: *** ; p < .01: ** ; p < .05: *",
                       threeparttable = TRUE, escape = FALSE) %>% 
  kableExtra::landscape()

```


# Scatterplots with with regression equation

```{r scatterplots-with-regeq}

two_fac_maize <- two_fac_maize %>% 
  rename_all(function(x)stringr::str_replace_all(x, "/", "_"))
  
# two_fac_maize %>% 
#   map_lgl(is.numeric) %>% 
#   which() %>% 
#   names() %>% 
#   list() %>% 
#   rep(times = 2) %>% 
#   set_names(nm = c("Var1", "Var2")) %>% 
#   cross_df()

numeric_trait_names <- two_fac_maize %>% 
  map_lgl(is.numeric) %>% 
  which() %>% 
  names()

signif_cor <- correlation(two_fac_maize[, numeric_trait_names]) %>% pluck("pvalue") %>% 
  as.data.frame() %>% 
  # rownames_to_column() %>% 
  map_df(.f = ~ .x < 0.05) %>% 
  map(which) 
  # map_int(length) %>% 
  # sum()
  
my.formula <- y ~ x

# ggplot2 mapper
library(ggpmisc)
map(numeric_trait_names[13:18], 
    function(x){
      walk(numeric_trait_names[signif_cor[[x]]],
          function(y){
            gcor <- ggplot(data = two_fac_maize, 
                   aes(x = get(x), 
                       y = get(y))) +
              geom_smooth(method = "lm", 
                          se=FALSE, color="black", 
                          formula = my.formula) +
              stat_poly_eq(formula = my.formula, 
                           aes(label = paste(..eq.label.., 
                                             ..rr.label.., sep = "~~~")), 
                           parse = TRUE) +
              geom_point() +
              xlab(x) +
              ylab(y) + 
              theme_bw() 
              ggsave(paste("./correlation_scatterplots/", x, y, ".png", sep = ""), plot = gcor)
          })
    })

```


```{r find-combination}
two_fac_maize %>%
  map_lgl(is.numeric) %>%
  which() %>%
  names() %>%
  list() %>%
  rep(times = 2) %>%
  set_names(nm = c("Var1", "Var2")) %>%
  cross_df()

numeric_trait_names <- two_fac_maize %>% 
  map_lgl(is.numeric) %>% 
  which() %>% 
  names()

correl_coef <- correlation(two_fac_maize[, numeric_trait_names]) %>% 
  pluck("pvalue") %>% 
  as.data.frame()

signif_cor <- correl_coef %>% 
  # rownames_to_column() %>% 
  map_df(.f = ~ .x < 0.05) %>% 
  map(which)

signif_combn <- data.frame(V2 = map(signif_cor, ~ numeric_trait_names[.x]) %>% 
             unlist(use.names = FALSE), 
           V1 = map2(.x = numeric_trait_names, 
                     .y = map_int(signif_cor, length), 
                     .f = ~ rep(.x, times = .y)) %>% unlist(use.names = FALSE)) %>% 
  select(V1, V2)

all_combn <- numeric_trait_names %>% 
  combn(m = 2) %>% 
  t() %>% 
  as_tibble()

to_retain_names <- dplyr::semi_join(signif_combn, all_combn) %>% 
  unite(sep = "", remove = TRUE, col = "plotname") %>% 
  pull(plotname) %>% 
  paste(".png", sep = "")

dir_loc <- "./correlation_scatterplots/"
list.files(dir_loc, full.names = TRUE)[list.files(dir_loc) %in% to_retain_names] %>% 
  file.rename(to = paste("./correlation_scatterplots_removed/", 
                         list.files(dir_loc, full.names = FALSE)[list.files(dir_loc) %in% to_retain_names], sep = ""))
```

