---
title: "Analysis of three way split-split plot design"
author: "Deependra Dhakal"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    toc: yes
    toc_depth: 3
    keep_tex: yes
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
- \usepackage{xcolor}
- \usepackage{rotating}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{subfig}
- \usepackage[format=hang,labelfont=bf,margin=0.5cm,justification=centering]{caption}
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
knitr::opts_chunk$set(tidy = TRUE, cache = TRUE, 
                      echo = FALSE, 
                      tidy.opts = list(width.cutoff=50), 
                      eval = TRUE, warning = FALSE, message = FALSE,
                      # fig.show = "hold", 
                      fig.align = "center", fig.width = 5,
                      fig.asp = 0.9, out.width = "0.7\\linewidth")
options(knitr.kable.NA = "", digits = 3)
# require(lmerTest)
require(agricolae)
require(nlme)
```


```{r load-data}
set.seed(9845333)

# read data and convert to correct types
monica_thesis1 <- readxl::read_xls("./monica_thesis.xls", "Sheet5") %>% 
  mutate_at(vars(`Rep`, `MainPlot_A`, `SubPlot_B`, `SubSubPlot_C`), as.factor)
monica_thesis2 <- readxl::read_xls("./monica_thesis.xls", "Sheet2", range = "A1:AD25") %>% 
  mutate_at(vars(`Rep`, `MainPlot_A`, `SubPlot_B`, `SubSubPlot_C`), as.factor)
monica_thesis3 <- readxl::read_xls("./monica_thesis.xls", "Sheet1") %>% 
  mutate_at(vars(`Rep`, `MainPlot_A`, `SubPlot_B`, `SubSubPlot_C`), as.factor)

monica_thesis1 <- readxl::read_xlsx("./cgr.xlsx", "Sheet1", range = "A1:AD25") %>% 
  mutate_at(vars(`Rep`, `MainPlot_A`, `SubPlot_B`, `SubSubPlot_C`), as.factor)

# calculate grand mean of each column and write to csv file
monica_thesis1 %>% 
  select_if(is.numeric) %>% 
  colMeans() %>% 
  c(monica_thesis2 %>%
              select_if(is.numeric) %>%
              colMeans()) %>%
  c(monica_thesis3 %>%
              select_if(is.numeric) %>%
              colMeans()) %>%
  bind_rows() %>% 
  t() %>% 
  as.data.frame() %>% 
  magrittr::set_colnames("Grand mean") %>% 
  rownames_to_column(var = "Trait") %>% 
  write_csv("grand_mean_cgr.csv", na = "")

# read cgr data and convert to correct types
monica_thesis1 <- readxl::read_xlsx("./cgr.xlsx", "Sheet1", range = "A1:AD25") %>% 
  mutate_at(vars(`Rep`, `MainPlot_A`, `SubPlot_B`, `SubSubPlot_C`), as.factor)

monica_thesis1 <- monica_thesis1 %>%
  rename_all(function(x)stringr::str_replace_all(x, "\ ", "_")) # replace all spaces with underscores
dep_vars <- monica_thesis1 %>% map_lgl(is.numeric) %>% which() %>% names()

```


# Analysis of 2 factorial RCBD

Since you have 3 levels for one factor and 3 levels for the other, data from an RCBD with 3 replications would be analysed as follows:

```{r design-and-book, results='asis'}

knitr::kable(monica_thesis1[,1:4], 
             format = "latex", 
             caption = "Design field book of a two factorial RCBD experiment", 
             digits = 3, booktabs = TRUE,
             col.names = c("Rep", "Main plot factor", 
                           "Sub plot factor", "Sub sub plot factor"), 
             align = 'l') %>% 
  kableExtra::kable_styling(latex_options = c("striped", 
                                              "hold_position", "scale_down"), 
                            full_width = TRUE, font_size = 11, position = "left")
```


# Analyis

```{r analysis-and-results}

# Example simple linear model specification
mon_model_lm <- lm(GY_per_net_plot ~
     Rep +
     MainPlot_A/SubPlot_B + 
     SubPlot_B/SubSubPlot_C +
     MainPlot_A/SubPlot_B/SubSubPlot_C +
     MainPlot_A * SubPlot_B * SubSubPlot_C+
     SubSubPlot_C,
   data = monica_thesis1) # caution: F-statistic calculated from overall residuals is unreliable

mon_model_lm %>% 
  anova() %>% 
  broom::tidy() %>% 
  mutate(significance = case_when(p.value <= 0.0001 ~ "***", 
                                  p.value <= 0.001 ~ "**", 
                                  p.value <= 0.05 ~ "*", 
                                  p.value <= 0.1 ~ ".",
                                  TRUE ~ NA_character_))

# Example manually specified error structure
mon_model_aov<-aov(GY_per_net_plot~MainPlot_A*SubPlot_B*SubSubPlot_C+
                     Error(Rep/MainPlot_A/SubPlot_B/SubSubPlot_C), data = monica_thesis1)

# Example Random effects model  
mon_model_lme<-lme(GY_per_net_plot~MainPlot_A*SubPlot_B*SubSubPlot_C, 
                   data=monica_thesis1, random=(~1|Rep/MainPlot_A/SubPlot_B/SubSubPlot_C))

summary(mon_model_lme)
coef(mon_model_lme)
ranef(mon_model_lme)
fixef(mon_model_lme)
mon_model_lme %>% 
  anova()

# # Manually specified models list
# mon_spp.plot <- map(dep_vars,
#                      .f = ~ aov(get(.x)~MainPlot_A*SubPlot_B*SubSubPlot_C+
#                                   Error(Rep/MainPlot_A/SubPlot_B/SubSubPlot_C), 
#                                 data = monica_thesis1))

# agricolae::ssp.plot does the same
model_list_spp <- map(dep_vars, 
                    .f = ~ with(monica_thesis1, 
                                ssp.plot(block = Rep, pplot = MainPlot_A, 
                                         splot = SubPlot_B, ssplot = SubSubPlot_C, 
                                         get(.x))))

means_mA <- map2(.x = dep_vars, .y = model_list_spp,
    .f = ~with(monica_thesis1, LSD.test(get(.x), MainPlot_A,
                             .y$gl.a, .y$Ea, console=FALSE)))

means_mB <- map2(dep_vars, .y = model_list_spp,
    .f = ~with(monica_thesis1, LSD.test(get(.x), SubPlot_B,
                             .y$gl.b, .y$Eb, console=FALSE)))

means_mC <- map2(dep_vars, .y = model_list_spp,
    .f = ~with(monica_thesis1, LSD.test(get(.x), SubSubPlot_C,
                             .y$gl.c, .y$Ec, console=FALSE)))

# dependent vars about "CGR"
cgr_dep_subsets <- str_subset(dep_vars, "CGR")

# obtaining crossed means
monica_thesis1 %>% 
  select(1:4, contains("CGR")) %>% 
  group_by(MainPlot_A, SubPlot_B, SubSubPlot_C) %>% 
  summarise_if(is.numeric, funs(mean, .args = list(na.rm = TRUE)))

# obtaining all the params in a list
contrast_means_spp <- purrr::pmap(.l = list(means_mA, means_mB, means_mC), 
     .f = function(a, b, c){a$"groups" %>% 
         rownames_to_column() %>% 
         bind_rows(b$"groups" %>% 
                     rownames_to_column()) %>% 
         bind_rows(c$"groups" %>% 
                     rownames_to_column())}
)

# # obtaining all the params in a df
# means_mA %>% map_df(.f = ~ .x %>% 
#                        pluck("groups") %>% 
#                        rownames_to_column(var = "Treatment") %>% 
#                        rename("Mean" = "get(.x)")) %>% 
#   bind_cols(means_mB %>% map_dfr(.f = ~ .x %>% 
#                                    pluck("groups") %>% 
#                                    rownames_to_column(var = "Treatment") %>%
#                                    rename("Mean" = "get(.x)"))) %>% 
#   bind_cols(means_mC %>% map_dfr(.f = ~ .x %>% 
#                                    pluck("groups") %>% 
#                                    rownames_to_column(var = "Treatment") %>%
#                                    rename("Mean" = "get(.x)"))) 

contrast_means_spp <- contrast_means_spp %>% 
  purrr::reduce(left_join, by = "rowname") %>% 
  magrittr::set_colnames(c("Treatment", paste(rep(dep_vars, each = 2), c("", "group"))))

contrast_means_spp %>% 
  write_csv("table_of_")

# cvs of all traits
monica_trait_cv_MainPlot <- data.frame(trait = dep_vars, 
                          cv = means_mA %>% 
                            map_dbl(.f = ~.x$statistics$CV))
monica_trait_cv_SubPlot <- data.frame(trait = dep_vars, 
                          cv = means_mB %>% 
                            map_dbl(.f = ~.x$statistics$CV))
monica_trait_cv_SubSubPlot <- data.frame(trait = dep_vars, 
                          cv = means_mC %>% 
                            map_dbl(.f = ~.x$statistics$CV))

```


```{r simplify-ssp-to-rcbd, results="asis"}

# design a factorial rcbd
# cross_df(list(mainplot = c("ml1", "ml2"),
#               subplot = c("sp1", "sp2"), 
#               subsubplot = c("ssp1", "ssp2")))

# design a factorial rcbd
# design.ab(trt = c(2, 2, 2), r = 3, design = "rcbd", randomization = TRUE)

three_factorial_model <- lm(`PH(cm)`~ Rep + MainPlot_A * SubPlot_B * SubSubPlot_C, data = monica_thesis1)
three_factorial_model %>% anova()
stargazer::stargazer(three_factorial_model, type = "latex", title = "Summary of Three factorial RCBD for trait")

# gets means for three way interactions
LSD.test(three_factorial_model, c("MainPlot_A", "SubPlot_B", "SubSubPlot_C"), 14, 13.2, 0.05, console = TRUE)

# gets means for minplot
LSD.test(three_factorial_model, c("MainPlot_A"), 14, 13.2, 0.05, console = TRUE)

# gets means for subplot
LSD.test(three_factorial_model, c("SubPlot_B"), 14, 13.2, 0.05, console = TRUE)

# gets means for subsubplot
LSD.test(three_factorial_model, c("SubSubPlot_C"), 14, 13.2, 0.05, console = TRUE)

# gets means for two way interactions
LSD.test(three_factorial_model, c("SubPlot_B", "SubSubPlot_C"), 14, 13.2, 0.05, console = TRUE)
LSD.test(three_factorial_model, c("MainPlot_A", "SubSubPlot_C"), 14, 13.2, 0.05, console = TRUE)
LSD.test(three_factorial_model, c("MainPlot_A", "SubPlot_B"), 14, 13.2, 0.05, console = TRUE)

# compile all models in the list below
model_list <- map(dep_vars, 
                    .f = ~ lm(get(.x) ~ Rep + 
                                MainPlot_A * SubPlot_B * SubSubPlot_C, 
                              data = monica_thesis1))

model_anova <- map(model_list, 
                   .f = ~anova(.x))

contrasts_list <- list(c("MainPlot_A", "SubPlot_B", "SubSubPlot_C"), 
     c("SubPlot_B", "SubSubPlot_C"), 
     c("MainPlot_A", "SubSubPlot_C"), 
     c("MainPlot_A", "SubPlot_B"), 
     "MainPlot_A", "SubPlot_B", "SubSubPlot_C")

contrast_means_all <- map2(.x = model_list, 
                           .y = model_anova,
                          .f = ~ map(contrasts_list, 
                                     .f = function(m)LSD.test(.x, m, 
                                                              .y$Df[[9]], .y$`Mean Sq`[[9]], 
                                                              0.05, console = FALSE)))

contrast_means_all_df <- map2(contrast_means_all, 
     dep_vars, 
     .f = ~ map_dfr(1:7, # gets df of all contrasts means binded rowwise
                .f = function(m) .x[[m]]$groups%>% 
                  rownames_to_column() %>% 
                  set_names(c("Comparison", 
                              .y, paste(str_trunc(.y, 10, ellipsis = "."), 
                                        "_groups", sep = ""))))) %>% 
  reduce_right(.f = left_join, by = "Comparison")

contrast_means_all_df %>% 
  write_csv(path = "./outputs/rcbd/mean_comparison_sheet3.csv", na = "")

# write RCBD anova to csv
walk2(.x = model_anova,
      .y = dep_vars %>% stringr::str_replace_all("_", " "),
      .f = ~.x %>% 
        rownames_to_column("Source of Variation") %>% 
        add_row() %>% 
        add_column(.before = 1, 
                   Trait = c(.y, rep(NA, times = (nrow(.)-1)))) %>%
        write_csv(path = "./outputs/rcbd/anova_test_results_sheet3.csv",
                  # row.names = FALSE,
                  na = "", append = TRUE, col_names = TRUE))

tibble(Traits = dep_vars, 
       CV = map_dbl(.x = model_list, 
                    .f = ~.x %>% 
                      cv.model())) %>% 
  write_csv("./outputs/rcbd/cv_sheet3.csv")
```


```{r saving-ssp-csv, eval=FALSE}

# write model cvs to csv
monica_trait_cv_MainPlot %>% write_csv(path = "cv_results_MainPlot.csv")
monica_trait_cv_SubPlot %>% write_csv(path = "cv_results_SubPlot.csv")
monica_trait_cv_SubSubPlot %>% write_csv(path = "cv_results_SubSubPlot.csv")

# write a single LSD means file to csv
monica_mean_traits %>%
  rename_all(function(x)stringr::str_replace_all(x, "_", " ")) %>% 
  write_csv(path = "LSD_means_result.csv",
            na = "")

# write a single ANOVA file to csv
walk2(.x = mon_ssp.plot,
      .y = dep_vars %>% stringr::str_replace_all("_", " "),
      .f = ~.x$`ANOVA` %>% 
        rownames_to_column("Source of Variation") %>% 
        add_row() %>% 
        add_column(.before = 1, 
                   Trait = c(.y, rep(NA, times = (nrow(.)-1)))) %>%
        write_csv(path = "anova_test_results.csv",
                  # row.names = FALSE,
                  na = "", append = TRUE, col_names = TRUE))

```


```{r manually-spec-error-model}
mon_model_aov %>% 
  broom::tidy() %>% 
  mutate(significance = case_when(p.value <= 0.0001 ~ "***", 
                                  p.value <= 0.001 ~ "**", 
                                  p.value <= 0.05 ~ "*", 
                                  p.value <= 0.1 ~ ".",
                                  TRUE ~ NA_character_)) %>% 
  rename(Treatment = stratum, DF = df, 
         SS = sumsq, MSS = meansq, 
         "F-value" = statistic, 
         "$Significance^{a}$" = significance) %>% # change notation of superscript
  mutate(header = case_when(term %in% "MainPlot_A" ~ 1,
                            term %in% c("MainPlot_A:SubPlot_B", "SubPlot_B") ~ 2, 
                            term %in% "Residuals" ~ 4, 
                            TRUE ~ 3)) %>% 
  arrange(header) %>% 
  mutate(term = ifelse(term == "Residuals", Treatment, term)) %>% 
  select(-p.value, -header, -Treatment) %>%
  rename(Treatment = term) %>% 
  mutate(Treatment = str_replace_all(Treatment, "_", " ")) %>% 
  # add_case(.before = 5, Treatment = "Residuals") %>% # use group_rows() from kableExtra
  # kableExtra::add_indent(positions = c(6:9)) %>%
  knitr::kable(format = "latex", 
               caption = "ANOVA of Grain yield per net plot", escape = FALSE) %>% 
  kableExtra::kable_styling(latex_options = "striped", full_width = FALSE, 
                            position = "left", font_size = 13) %>% 
  kableExtra::group_rows("Mainplot", start_row = 1, end_row = 1) %>% 
  kableExtra::group_rows("Subplot", start_row = 2, end_row = 3) %>% 
  kableExtra::group_rows("SubSubplot", start_row = 4, end_row = 7) %>% 
  kableExtra::group_rows("Residuals", start_row = 8, end_row = 11)
  # kableExtra::add_footnote(c("P-value <= 0.0001 = '***', \nP-value <= 0.001 = '**', \nP-value <= 0.05 = '*', \nP-value <= 0.1 = '.'"))
```


```{r three-factor-model-summary, results='asis', eval=FALSE}
# # must use this function with float=FALSE in stargazer
long_stargazer <- function(...){
  output <- capture.output(stargazer::stargazer(...))
  # The lines 4 and second last lines are the ones we want to remove...
  output[c(4, length(output)-1)] <- output[c(4, length(output)-1)] %>% 
    stringr::str_replace("tabular", "longtable")
  # cat out the results - this is essentially just what stargazer does too
  cat(paste(output, collapse = "\n"), "\n")
}

long_stargazer(two_fac_model,
               title = "Mean comparison of Post-harvest traits", 
               style = "all", digits = 2, 
               header = FALSE, font.size = "small", 
               column.labels = c("\\parbox[t]{2.0cm}{Days for Flowering}", 
                                 "\\parbox[t]{2.0cm}{Days for Fruit Set}",
                                 "\\parbox[t]{2.0cm}{Days for fruit set to Harvest}", 
                                 "\\parbox[t]{2.0cm}{Firmness}",
                                 "\\parbox[t]{2.0cm}{pulp weight}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 3 DAH}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 5 DAH}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 7 DAH}", 
                                 "\\parbox[t]{2.0cm}{PWL percent 9 DAH}", 
                                 "\\parbox[t]{2.0cm}{TSS}"), 
               model.names = TRUE, dep.var.labels.include = FALSE, 
               digits.extra = 3, align = TRUE, single.row = TRUE, 
               float.env = "table*",
               df = FALSE, omit.stat = c("adj.rsq"),
               column.sep.width = "1pt", float = TRUE)
```


# All results summary

```{r three-fac-groups-tab, results='asis', eval=FALSE}

walk2(.x = monica_mean_traits, 
      .y = dep_vars %>% 
        stringr::str_replace_all("_", "\ ") %>% 
        stringr::str_replace_all("%", "\\\\%"),
      .f = ~ knitr::kable(.x, 
                          caption = paste("Treatment means with groups of", .y),
                          format = "latex", longtable = TRUE,
                          digits = 2, booktabs = TRUE, 
                          align = 'l', escape = TRUE) %>% 
        kableExtra::kable_styling(latex_options = c("striped", 
                                                    "hold_position"), 
                                  font_size = 12, position = "left") %>% 
        print())
```

# Correlation matrix of numeric variables

```{r correlation-annotate}
# This function annotates the correlation coefficients 
# with the stars corresponding to the level of significance
# x is a matrix containing the data
# method : correlation method. "pearson"" or "spearman"" is supported
# removeTriangle : remove upper or lower triangle
# results : "html" or "latex" (default)
# align: a vector of alignment values as is specified in xtable(x, align)

large <- function(x){
  paste0('{\\footnotesize{\\bfseries ', x, '}}')
}

corstars <-function(x, align, caption, method=c("pearson", "spearman"), removeTriangle=c("upper", "lower"),
                    result=c("none", "html", "latex")){
  #Compute correlation matrix
  require(Hmisc)
  x <- as.matrix(x)
  correlation_matrix<-rcorr(x, type=method[1])
  R <- correlation_matrix$r # Matrix of correlation coeficients
  p <- correlation_matrix$P # Matrix of p-value 
  
  ## Define notions for significance levels; spacing is important.
  mystars <- ifelse(p < .0001, "****", ifelse(p < .001, "*** ", ifelse(p < .01, "**  ", ifelse(p < .05, "*   ", "    "))))
  
  ## trunctuate the correlation matrix to two decimal
  R <- format(round(cbind(rep(-1.11, ncol(x)), R), 2))[,-1]
  
  ## build a new matrix that includes the correlations with their apropriate stars
  Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x))
  diag(Rnew) <- paste(diag(R), " ", sep="")
  rownames(Rnew) <- colnames(x)
  colnames(Rnew) <- paste(colnames(x), "", sep="")
  
  ## remove upper triangle of correlation matrix
  if(removeTriangle[1]=="upper"){
    Rnew <- as.matrix(Rnew)
    Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
  }
  
  ## remove lower triangle of correlation matrix
  else if(removeTriangle[1]=="lower"){
    Rnew <- as.matrix(Rnew)
    Rnew[lower.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
  }
  
  ## remove last column and return the correlation matrix
  Rnew <- cbind(Rnew[1:length(Rnew)-1])
  if (result[1]=="none") return(Rnew)
  else{
    if(result[1]=="html") print(xtable(Rnew), type="html", comment = FALSE)
    else print(xtable(Rnew, auto = TRUE,  align = align, caption = caption), type="latex", 
               comment = FALSE, size = "\\footnotesize", 
               sanitize.colnames.function = large, 
               booktabs = TRUE, tabular.environment="longtable", 
               floating=FALSE)
  }
} 
```


```{r correlation-postharvest, results='asis'}
# crop yield and agro-morphology
cortable <- corstars(monica_thesis1 %>% 
                       select_at(which(map_lgl(., is.numeric))))
# # write to csv
# cortable %>% rownames_to_column(var = "traits") %>% write_csv("correlation_maize_results.csv")

# # html
# cortable %>%
#   knitr::kable(format = "html",
#                caption = "Pearson correlation coefficients of Post harvest traits",
#                booktabs = TRUE, align = "l"
#                # longtable = TRUE
#                ) %>%
#   kableExtra::kable_styling(font_size = 14, bootstrap_options = c("striped", "responsive")) %>%
#   # kableExtra::column_spec(1:11, width = "0.11\\\\textwidth") %>%
#   kableExtra::row_spec(0, bold = TRUE) %>%
#   kableExtra::column_spec(1, bold = TRUE) %>%
#   kableExtra::footnote(general = "p < .0001: **** ; p < .001: *** ; p < .01: ** ; p < .05: *",
#                        threeparttable = TRUE, escape = FALSE)

cortable %>%
  rename_all(function(x)stringr::str_trunc(x, width = 4, side = "c", ellipsis = "")) %>% 
  knitr::kable(format = "latex",
               caption = "Pearson correlation coefficients of Post harvest traits",
               booktabs = TRUE, align = "l"
               # longtable = TRUE
               ) %>%
  kableExtra::kable_styling(font_size = 14, latex_options = c("striped", "scale_down")) %>%
  # kableExtra::column_spec(1:11, width = "0.11\\\\textwidth") %>%
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::footnote(general = "p < .0001: **** ; p < .001: *** ; p < .01: ** ; p < .05: *",
                       threeparttable = TRUE, escape = FALSE) %>% 
  kableExtra::landscape()

```


# Scatterplots with with regression equation

```{r scatterplots-with-regeq, eval=FALSE}

monica_thesis1 <- monica_thesis1 %>% 
  rename_all(function(x)stringr::str_replace_all(x, "/", "_"))

numeric_trait_names <- monica_thesis1 %>% 
  map_lgl(is.numeric) %>% 
  which() %>% 
  names()

signif_cor <- correlation(monica_thesis1[, numeric_trait_names]) %>% pluck("pvalue") %>% 
  as.data.frame() %>% 
  # rownames_to_column() %>% 
  map_df(.f = ~ .x < 0.05) %>% 
  map(which) 
  # map_int(length) %>% 
  # sum()
  
my.formula <- y ~ x

# ggplot2 mapper
library(ggpmisc)
map(numeric_trait_names[13:18], 
    function(x){
      walk(numeric_trait_names[signif_cor[[x]]],
          function(y){
            gcor <- ggplot(data = monica_thesis1, 
                   aes(x = get(x), 
                       y = get(y))) +
              geom_smooth(method = "lm", 
                          se=FALSE, color="black", 
                          formula = my.formula) +
              stat_poly_eq(formula = my.formula, 
                           aes(label = paste(..eq.label.., 
                                             ..rr.label.., sep = "~~~")), 
                           parse = TRUE) +
              geom_point() +
              xlab(x) +
              ylab(y) + 
              theme_bw() 
              ggsave(paste("./correlation_scatterplots/", x, y, ".png", sep = ""), plot = gcor)
          })
    })

```


```{r find-combination, eval=FALSE}
monica_thesis1 %>%
  map_lgl(is.numeric) %>%
  which() %>%
  names() %>%
  list() %>%
  rep(times = 2) %>%
  set_names(nm = c("Var1", "Var2")) %>%
  cross_df()

numeric_trait_names <- monica_thesis1 %>% 
  map_lgl(is.numeric) %>% 
  which() %>% 
  names()

correl_coef <- correlation(monica_thesis1[, numeric_trait_names]) %>% 
  pluck("pvalue") %>% 
  as.data.frame()

signif_cor <- correl_coef %>% 
  # rownames_to_column() %>% 
  map_df(.f = ~ .x < 0.05) %>% 
  map(which)

signif_combn <- data.frame(V2 = map(signif_cor, ~ numeric_trait_names[.x]) %>% 
             unlist(use.names = FALSE), 
           V1 = map2(.x = numeric_trait_names, 
                     .y = map_int(signif_cor, length), 
                     .f = ~ rep(.x, times = .y)) %>% unlist(use.names = FALSE)) %>% 
  select(V1, V2)

all_combn <- numeric_trait_names %>% 
  combn(m = 2) %>% 
  t() %>% 
  as_tibble()

to_retain_names <- dplyr::semi_join(signif_combn, all_combn) %>% 
  unite(sep = "", remove = TRUE, col = "plotname") %>% 
  pull(plotname) %>% 
  paste(".png", sep = "")

dir_loc <- "./correlation_scatterplots/"
list.files(dir_loc, full.names = TRUE)[list.files(dir_loc) %in% to_retain_names] %>% 
  file.rename(to = paste("./correlation_scatterplots_removed/", 
                         list.files(dir_loc, full.names = FALSE)[list.files(dir_loc) %in% to_retain_names], sep = ""))
```

