\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Effect of fruit thinning and defoliation on yield and quality traits of Papaya (Carica papaya cv. Red Lady) in Chitwan, 2016},
            pdfauthor={Ramesh Upreti, Deependra Dhakal},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Effect of fruit thinning and defoliation on yield and quality traits of
Papaya (\emph{Carica papaya} cv. Red Lady) in Chitwan, 2016}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Ramesh Upreti, Deependra Dhakal}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{February 1, 2018}

\usepackage{dcolumn}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage[normalem]{ulem}
\usepackage{xcolor}
\usepackage{rotating}
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
\usepackage[format=hang,labelfont=bf,margin=0.5cm,justification=centering]{caption}
\usepackage{subcaption}
\newcommand{\subfloat}[2][need a sub-caption]{\subcaptionbox{#1}{#2}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Abstract}\label{abstract}

The effect of fruit thinning and defoliation on papaya, cultivar Red
Lady, was studied at commercial papaya orchard of Abloom Flora Farm,
Chanauli, Chitwan from January to December, 2016. This experiment was
laid out in factorial RCBD with nine treatment combinations (control
i.e.~no thinning + no defoliation, no thinning + 33\% defoliation, no
thinning + 66\% defoliation, hand thinning + no defoliation, hand
thinning + 33\% defoliation, hand thinning + 66\% defoliation, chemical
thinning by NAA 100 ppm + no defoliation, chemical thinning by NAA 100
ppm + 33\% defoliation, chemical thinning by NAA 100 ppm + 66\%
defoliation) replicating 3 times to know the effect of these treatments
on quality and yield. Fruit set, fruit size, fruit weight, yield,
physiological loss in weight percentage and firmness were found
significantly higher with hand thinning. Chemical thinning resulted in
significantly higher TSS, TSS/TA ratio along with slightly higher
ascorbic acid content and lower TA. However, chemical thinning showed
over thinning effect with higher abscission percentage and the lowest
yield. Defoliation treatments did not result in significant improvement
on yield and quality. The highest stem girth, leaf number, fruit
diameter, yield and firmness were recorded with 33\% defoliation. The
66\% defoliation treatment showed higher fruit drop/lower retention and
lower yield. These results suggest that hand thinning and 33\%
defoliation practice improves the fruit yield and quality of papaya.

\textbf{Key words}: \emph{Carica papaya}, fruit thinning, defoliation,
quality traits

\section{Introduction}\label{introduction}

Papaya (\emph{Carica papaya} L.) is one of most important fruit crop,
cultivated throughout the tropical and subtropical regions of the world,
belonging to the Caricaceae family (Da Silva et al., 2007). It is
believed to be originated from the lowlands of eastern Central America
from Mexico to Panama (Office of the Gene Technology Regulator
{[}OGTR{]}, 2008) perhaps in southern Mexico and Tropical America
(Shrestha, 2016). In western countries papaya is known as `wonder fruit
of tropics'. In Nepal and India it is regarded as `Kalpa Brikshya' due
to its nutrients enriched fruit and multipurpose plant. Christopher
Columbus even considered it as the `fruit of Angels' after discovering
it in tropical America. It was brought to India in the 16th century
(OGTR, 2008) thereafter it is believed to be introduced in Nepal before
four hundred years ago (Paudyal, Pandey \& Bhattarai, 2013) from India.
Out of 48 species known in Caricaceae, Carica papaya is only species
grown for edible fruits (Chadha, 1992). There are 6 genus in this family
and 35 species out of which 32 species are dioecious. Papaya is a single
hollow stemmed herbaceous, latex producing, short lived, plant (Jimenez,
Mora-Newcomer \& Gutierrez-Soto, 2014). Its stem reaches the height of
2-10 m, which is cylindrical spongy fibrous, loose, gray or gray-brown
color, 10-30 cm diameter and toughened by large and protuberant scars of
fallen leaves and flowers, terminating with a crown of large palmately
lobed leaves (Zhou, Christopher \& Paull, 2000; Medina, Gutierrez \&
Garcia, 2003).

Papaya is one among the fruits which has attained a great popularity in
recent years, because of gynodioecious nature, easy cultivation, quick
returns, adaptability to diverse soil and climatic conditions and
attractive delicious wholesome fruits having multifarious uses (Tandel,
Ahir \& Patel, 2017). Major papaya cultivated districts are Siraha,
Bara, Parsa, Dhanusha, Mahottari, Sarlahi, Rupandehi, Chitwan, Kailali,
Dang, Nawalparasi and Dhading. The productive area covered by papaya in
Nepal is 1,083 ha where production is 14,137 mt with the productivity of
13.05 mt/ha (Statistical information on Nepalese Agriculture, 2015/16).
Papaya is regarded as a good source of vitamin A, ascorbic acid,
beta-carotene, riboflavin, iron, calcium, thiamin, niacin, pantothenic
acid, vitamin B-6 and vitamin K (Saran \& Choudhary, 2013) which may
prevent cancer, diabetes, jaundice and heart disease. It is also
utilized in the pharmaceutical and cosmetic industries (Shrestha, 2016).
Production and quality of papaya are affected by climate, cultivar type
and cultural practices (Workneh, Azene \& Tesfay, 2012). Quality is the
state of well accepted external features (such as colour, shape, size
and freedom from defects) and internal attributes (like texture,
sweetness, acidity, aroma, flavour, shelf life and nutritional value) of
a product. Researches of papaya are found to be concentrated on the
varietal trials and production aspects, but quality improvement
practices are not much studied. Productivity and quality of papaya fruit
production is not satisfactory in Nepalese context. Little is known
about the influence of fruit thinning and defoliation in papaya.

Fruit thinning and defoliation practices could ensure better quality and
yield of papaya. The effect of defoliation and fruit thinning on plant
growth and development depends on the time and intensity of defoliation
and fruit thinning. (Pavel \& DeJong, 1993; Mulas, 1996). Fruit thinning
is the removal of fruitlets in heavy fruit set situations in plant
aiming to increase fruit sizes, avoid branch breakdown, reduce
harvesting costs, and promote a balance between the vegetative and
reproductive growth of plants (Peres, Martins, Barreto \& Pimentel,
2017). It is hundreds of year old practice for manipulating the cropping
and blooming of fruit plants like apple, pear and peach (Dennis, 2000).
Defoliation is simply the removal of leaves for easing cultural
practices and maintaining the physiological balance of plant. The
availability of carbohydrate or assimilates exported from leaves to
fruit determines papaya fruit production and sweetness. Partial
defoliation (33\% and 66\%) of grape cv. Cabernet Sauvignon, is an
endeavour to reduce vegetative growth and the source:sink ratio, to
stimulate metabolic activity and to improve canopy microclimate, induced
higher photosynthetic effectiveness of the remaining leaves as well as
an increase in assimilate supply to the bunches (Hunter \& Visser,
1988). According to Awada (1967), it was found that defoliation
increases papaya staminate flower number and decreases trunk growth and
leaf dry weight (DW), whereas deflowering decreases staminate flower
number and increases trunk growth and leaf DW (Zhou et al., 2000).
Photosynthetic organs in the plant (mature leaves) are known as sources,
while non-photosynthetic organs (fruits, roots and tubers) and immature
leaves are known as sinks (Taiz \& Zeiger, 2006). Source-sink balance
was found critical for papaya fruit set, development, and sugar
accumulation (Zhou et al., 2000). Therefore, this study was carried out
to study the effect of fruit thinning and defoliation on yield and yield
attributing characters of papaya and to assess the improvement in fruit
quality due to fruit thinning and defoliation.

\section{Materials and methods}\label{materials-and-methods}

\subsection{Site of study}\label{site-of-study}

This study was conducted at commercial Papaya farm (Abloom flora farm)
of Chanauli, Chitwan, Nepal during January to December 2016. It is
situated at 27° 37' 3" North latitude and 84° 17' 43" East longitudes
and at an elevation of 175 meters from the sea level. The climate of the
site can be characterized as tropical with minimum and maximum
temperatures ranging from 9-370 C with the average rainfall of 2520 mm.
The soil of the experimental site was sandy loam with slightly acidic
(5.6) pH. The postharvest quality analysis of fruit was done in the
post-harvest laboratory of Agriculture and Forestry University (AFU) in
the month October to December, 2016.

\subsection{Selection of the cultivar}\label{selection-of-the-cultivar}

Experiment was conducted using a high yielding, gynodioecious and early
maturing variety `Red Lady' of Taiwanese origin. It was propagated
through seed which was planted in plastic tray using cocopit in the
nursery. Healthy, disease free and uniform seedlings of 45 days age were
transplanted in a rectangular system of 2 meter row to row distance and
1.8 m plant to plant distance and subjected to uniform cultural
practices before and during the field trial.

\subsection{Experimental design}\label{experimental-design}

A two factorial randomized complete block design (RCBD) was used with
three replications and nine treatments combinations. The first factor is
fruit thinning, which include control (not treated), hand thinning
(retaining one fruit per node), and chemical thinning (using 100 ppm of
NAA). The second factor is defoliation, which include control (not
treated), thirty three percent defoliation (33\% leaves are removed
using secateurs), and sixty six percent defoliation (66\% leaves are
removed with secateurs). Two plants were selected for each treatment and
altogether there were 54 plants.

\subsubsection{Treatment combinations}\label{treatment-combinations}

Two groups of treatment factors were employed in the study, each with 3
levels. Table \ref{tab:treat-comb} shows various combinations that
comprised total number of treatments.

\rowcolors{2}{gray!6}{white}

\begin{table}[!h]

\caption{\label{tab:treat-comb}Treatment combination of the RCBD experiment with two factors}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}{l}
\hiderowcolors
\toprule
Treatment combination\\
\midrule
\showrowcolors
No thinning+33\% defoliation\\
Hand thinning+33\% defoliation\\
Chemical thinning+33\% defoliation\\
No thinning+66\% defoliation\\
Hand thinning+66\% defoliation\\
\addlinespace
Chemical thinning+66\% defoliation\\
No thinning+No defoliation\\
Hand thinning+No defoliation\\
Chemical thinning+No defoliation\\
\bottomrule
\end{tabular}
\end{table}

\rowcolors{2}{white}{white}

\subsubsection{Layout of field
experiment}\label{layout-of-field-experiment}

A layout of the experimental design, with 9 treatment combinations each
replicated thrice, is shown below in Figure \ref{fig:design-layout}.

\begin{figure}

{\centering \includegraphics[width=0.95\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/design-layout-1} 

}

\caption{Layout of experimental design}\label{fig:design-layout}
\end{figure}

\subsection{Treatment formulation}\label{treatment-formulation}

\subsubsection{Timing}\label{timing}

Treatments were applied on 20th of May, 130 days after transplanting
(DAT). Chemical thinning was done two times by spraying 100 ppm NAA to a
state where run-off could be observed with an electric sprayer on May 20
and June 5, 2016. Hand thinning was applied weekly after May 20 (130
DAT) for two months. Defoliation was practiced only once (in which 33\%
and 66\% leaves were removed out of total leaves) on May 20, 2016.

\subsubsection{Preparation and
application}\label{preparation-and-application}

\textbf{Control (No thinning + no defoliation)}

In this treatment, plants are not treated, and retained to natural
growth condition providing all essential cultural practices.

\textbf{Hand thinning}

It was done by twisting and plucking fruits of 3-5 cm size, retaining
one fruit per node (Zhou et al., 2000), at weekly interval for two
months. After removing small fruits by hand thinning, paper towel was
used to prevent the latex exudation from leaking on to the low laying
fruits.

\textbf{Chemical thinning by NAA (100 ppm)}

One gram of NAA (Alpha-Naphthalene acetic acid, HIMEDIA Lot no.
0000132888, GRM575-25G) was dissolved in 5 ml ethanol + one liter
distilled water (Aghaei, Bahramnejad, \& Mozafari, 2013), and stock
solution of 1000 ppm was prepared at post-harvest laboratory of
Agriculture and Forestry University (AFU). In the field, it was diluted
to 100 ppm working solution by adding 9 liter of distilled water in the
stock solution of 1 liter. Then, it was sprayed over the whole plant
with the help of hand sprayer (electric) until all the leaves were
completely wet to runoff (Subhadrabandhu, Thongplew, \& Wasee, 1997),
initially after first fruit set and then for second time after fifteen
days of first application.

\textbf{Defoliation}

Total numbers of leaves were counted on individual plant and 33\% and
66\% of total leaves was calculated in accordance with treatments. Then
defoliation was done from lower part of plant, i.e oldest to new leaves
were removed (Zhou et al., 2000), retaining petiole on the plants by
secateurs.

\subsection{Physical and physiological properties associated with
flowering and
fruiting}\label{physical-and-physiological-properties-associated-with-flowering-and-fruiting}

\textbf{Flower and fruit drop (\%)}

Total number of abscised flower buds and fruits of size less than 3 cm
were counted. Thus, the percentage of fruit retained was calculated as:

\[
Fruit~retention \% = \left [ 1-\frac{Total~number~of~abscised~fruitlets/flowers}{Total~number~of~flowers~set}\right ] \times 100
\]

\textbf{Yield per plant (\(kg\))}

Yield of total fruits harvested in different intervals from the sample
plants in each treatment was recorded and average was worked out. It was
calculated by total number of fruit set multiplied by average weight of
fruit for each treatment and expressed in kilogram per plant.

\[Yield = Total~fruit~set~\times~average~weight~of~fruit\]

\textbf{Fruit weight (\(g\))}

Five fruits obtained from each plant of same treatment were individually
measured with the help of electronic balance and finally average weight
of five fruits was taken at the time of laboratory analysis.

\textbf{Seed weight (\(g\))}

Seed weight was measured by electronic balance after peeling and cutting
the fruit at the time of laboratory analysis.

\textbf{Fruit length (\(cm\))}

Average length of five fruits obtained from two plants of each treatment
was measured using measuring tape between base and apex of the fruit and
expressed in centimeters.

\textbf{Fruit breadth (\(cm\))}

Average breadth of five fruits obtained from two plants of each
treatment was measured at the equatorial region using measuring tape and
expressed in centimeters.

\textbf{Fruit Firmness (\(kg~cm^2\))}

Firmness was measured with Effigi Penetrometer (FT - 327, Italy). A
slice of about one inch thickness was cut out on blush and non-blush
sides of the fruit and 11 mm tip plunger was inserted into a depth of
7.9 mm until the reading was taken (n=10).

\textbf{Physiological loss in weight (\%)}

It was done by taking initial weight on the day of harvest followed by
taking weight on each alternate day during the storage period.

\[Physiological~weight~loss~\% =\frac{Initial~weight-Final~weight}{Initial~weight}\times 100\]

\subsection{Chemical properties associated with
fruiting}\label{chemical-properties-associated-with-fruiting}

\textbf{Total soluble solids (\(Brix~value\))}

The TSS content of the fruits was analyzed at the post harvest
laboratory of AFU, Rampur. For TSS, the fruit pulp (without peel and
seed) was homogenized in a blender and measured with a hand
Refractometer (ERMA Inc., Tokyo, Japan) using juice extracted directly
from the pulp and expressed as °Brix. Correction on the TSS was made
according to temperature of the laboratory as mentioned by Saini,
Sharma, Dhankhar and Kaushik (2001).

\textbf{Titratable Acidity (\%)}

The Titratable Acidity (TA) content of the fruit was analyzed at the
post harvest laboratory of AFU, Rampur. It was determined from 10 ml
fruit juice diluted in 50 ml distilled water, titrated with 0.1 N NaOH
using phenolpthalein indicator (2-3 drops), and calculated as percent
citric acid. Percent titrable acidity was calculated by using the
following formula as suggested by Saini et al. (2001).

\[TA \% = \frac{Volume~of~NaOH~\times~Normality~of~NaOH~\times~0.0064}{volume~of~juice~titrated}\times 100\]

\begin{itemize}
\tightlist
\item
  Acid milliequivalents (mEq) factor for citric acid
\end{itemize}

\textbf{TSS/TA ratio}

The ratio of TSS and TA was computed and recorded.

\textbf{Vitamin C (Ascorbic acid) content (mg/100 g sample)}

The ascorbic acid content of ripe fruits was determined by volumetric
analysis with dye 2-6 dichloro-phenolindophenol. Initially, following
solutions of titrant, titrand and dyes were prepared:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{Oxalic acid solution}: 4 \% Oxalic acid solution was prepared
  with 4 g Oxalic acid in 100 ml distilled water.
\item
  \emph{Dye solution}: It was prepared by mixing 21 mg sodium
  bi-carbonate with the small volume of water and dissolving 26 mg 2,
  6-dichlorophenol indophenols in it making 100 ml with distilled water.
\item
  \emph{Standard solution}: It was prepared by dissolving 100 mg (0.1 g)
  ascorbic acid in 100 ml of 4 \% oxalic acid solution in a standard
  flask.
\item
  \emph{Working solution}: 10 ml of stock standard solution was diluted
  to 100 ml of 4 \% oxalic acid to prepare working standard solution.
  The concentration of working standard solution was maintained at 100
  \(\mu g\) per ml.
\end{enumerate}

After preparing the working solution, 5 ml of working solution was
pipette out in a 100 ml of conical flask and 10 ml of 4 \% Oxalic acid
was added to titrate against the dye (V1). End point (appearance of the
pink color which persists for a few minutes) was noticed. The amount of
dye consumed was expressed in equivalence of amount of ascorbic acid. 2
ml papaya juice was extracted from sample in a centrifugal tube and 10
ml of 4 \% Oxalic acid solution was added to it to make known volume of
solution. This solution was centrifuged for 5 minutes. Then, 5 ml of
centrifuged supernatant solution was pipette out without any residue and
10 ml of 4 \% Oxalic acid solution was added to it. Finally, it was
titrated against the dye solution (V2).

The ascorbic acid was calculated using following known relation:
\[Ascorbic~acid~(mg/100~g~sample) = \frac{0.5~mg~\times~V2~\times~12~ml}{V1\times 5ml\times~Weight~of~sample~(ml)}\]
Where, V1 and V2 are the volume of dye consumed during titration.

\subsection{Statistical method}\label{statistical-method}

For each response variable, fixed effects linear terms were fitted with
both ``Fruit thinning'' and ``Defoliation'' factors. Apart from that,
Replication effects were also contrasted for each level of the design
factor. The representation of model in vector space is shown in Equation
\eqref{eq:linear-model-form}

\begin{equation}
Y_{hijt} = \mu + \theta_{h} + \tau_{ij} + \sigma_{hijt}
\label{eq:linear-model-form}
\end{equation}

Where, \(\mu\) is the sample mean across treatments, \(\tau_{ij}\) is
the treatment combination main effects and interaction effects.
\(\tau_{ij}\) can also be expressed in terms of \(\gamma_i\) (the effect
of factor A at level \(i\)), \(\delta_j\) (the effect of factor B at
level \(j\)), and \((\gamma\delta)_{ij}\) (the effect of interaction of
factor A at \(i^{th}\) level and factor B at \(j^{th}\) level.)

Experimental data were analyzed using R-stat software, and therein,
treatment means were separated using Duncan's Multiple Range Test (DMRT)
at 5\% level of significance. Analysis of variance (ANOVA) was used to
test differences among the factors and the overall effectiveness of
blocking. Only when a significant treatments' effects could verified
(through F-statistic), multiple range test was employed.

Similarly, traits were checked for their associatedness using
correlation coefficients as the measure. High degree of linear
association among variables (recorded independently) would warrant a
thorough inspection for usefulness in later analysis.

\section{Results and discussion}\label{results-and-discussion}

\subsection{Model summary of fruit retention and fruit yield
traits}\label{model-summary-of-fruit-retention-and-fruit-yield-traits}

Treatment coefficients of fruit yield and fruit retention traits as
obtained from the model described in Equation \eqref{eq:linear-model-form}
is presented in Table \ref{tab:model-summary1}.

\begingroup  \small 

\begin{longtable}{@{\extracolsep{-10pt}}lD{.}{.}{-2} D{.}{.}{-2} } 
\caption{\label{tab:model-summary1}Model summary of fruit retention and fruit yield}\\
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{2}{c}{\textit{Dependent variable:}} \\ 
\cline{2-3} 
\\[-1.8ex] & \multicolumn{2}{c}{\textit{OLS}} \\ 
 & \multicolumn{1}{c}{\parbox[t]{2.50cm}{Fruit retention}} & \multicolumn{1}{c}{\parbox[t]{2.50cm}{Fruit yield}} \\ 
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)}\\ 
\hline \\[-1.8ex] 
 66% defoliation & -11.60$ $(9.83) & 2.58$ $(7.53) \\ 
  & p = 0.26 & p = 0.74 \\ 
  No defoliation & -17.80^{*}$ $(9.83) & -4.80$ $(7.53) \\ 
  & p = 0.09 & p = 0.54 \\ 
  Hand thinning & -11.50$ $(9.83) & 6.77$ $(7.53) \\ 
  & p = 0.27 & p = 0.39 \\ 
  Chemical thinning & -21.80^{**}$ $(9.83) & -16.70^{**}$ $(7.53) \\ 
  & p = 0.05 & p = 0.05 \\ 
  Replication1 & -1.78$ $(5.67) & -0.36$ $(4.35) \\ 
  & p = 0.76 & p = 0.94 \\ 
  Replication 2 & 3.60$ $(5.67) & 8.03^{*}$ $(4.35) \\ 
  & p = 0.54 & p = 0.09 \\ 
  66% Defoliation + Hand thinning & 15.30$ $(13.90) & 3.35$ $(10.60) \\ 
  & p = 0.29 & p = 0.76 \\ 
  No defoliation + Hand thinning & 20.10$ $(13.90) & -7.93$ $(10.60) \\ 
  & p = 0.17 & p = 0.47 \\ 
  66% defoliation + Chemical thinning & 8.83$ $(13.90) & -4.59$ $(10.60) \\ 
  & p = 0.54 & p = 0.68 \\ 
  No defoliation + Chemical thinning & 17.50$ $(13.90) & 0.77$ $(10.60) \\ 
  & p = 0.23 & p = 0.95 \\ 
  Constant & 45.70^{***}$ $(7.68) & 49.30^{***}$ $(5.89) \\ 
  & p = 0.00003 & p = 0.00000 \\ 
 \hline \\[-1.8ex] 
Observations & \multicolumn{1}{c}{27} & \multicolumn{1}{c}{27} \\ 
R$^{2}$ & \multicolumn{1}{c}{0.42} & \multicolumn{1}{c}{0.73} \\ 
Residual Std. Error & \multicolumn{1}{c}{12.00} & \multicolumn{1}{c}{9.22} \\ 
F Statistic & \multicolumn{1}{c}{1.18  (p = 0.37)} & \multicolumn{1}{c}{4.38$^{***}$  (p = 0.005)} \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{2}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{longtable}

\endgroup  

\subsection{ANOVA of fruit retention and fruit yield
traits}\label{anova-of-fruit-retention-and-fruit-yield-traits}

ANOVA of the trait variables -- fruit retention and fruit yield --
described by the model, in Equation \eqref{eq:linear-model-form}, are
presented in Table \ref{tab:model-anova1} and Table
\ref{tab:model-anova2}, respectively.

\begingroup\fontsize{10}{12}\selectfont
\rowcolors{2}{white}{gray!6}

\begin{longtable}{>{\raggedright\arraybackslash}p{10em}lllll}
\caption{\label{tab:model-anova1}ANOVA of Fruit retention percent}\\
\hiderowcolors
\toprule
term & df & sumsq & meansq & statistic & p.value\\
\midrule
\endfirsthead
\caption[]{\label{tab:model-anova1}ANOVA of Fruit retention percent \textit{(continued)}}\\
\toprule
term & df & sumsq & meansq & statistic & p.value\\
\midrule
\endhead
\
\endfoot
\bottomrule
\endlastfoot
\showrowcolors
Defoliation & 2 & 129 & 64.5 & 0.45 & 0.65\\
Fruit\_thinning & 2 & 1052 & 525.9 & 3.63 & 0.05\\
Replication & 2 & 135 & 67.7 & 0.47 & 0.63\\
Defoliation:Fruit\_thinning & 4 & 395 & 98.6 & 0.68 & 0.62\\
Residuals & 16 & 2317 & 144.8 &  & \\*
\end{longtable}

\rowcolors{2}{white}{white}\endgroup{}

\begingroup\fontsize{10}{12}\selectfont
\rowcolors{2}{white}{gray!6}

\begin{longtable}{>{\raggedright\arraybackslash}p{10em}lllll}
\caption{\label{tab:model-anova2}ANOVA of Fruit yield per plant}\\
\hiderowcolors
\toprule
term & df & sumsq & meansq & statistic & p.value\\
\midrule
\endfirsthead
\caption[]{\label{tab:model-anova2}ANOVA of Fruit yield per plant \textit{(continued)}}\\
\toprule
term & df & sumsq & meansq & statistic & p.value\\
\midrule
\endhead
\
\endfoot
\bottomrule
\endlastfoot
\showrowcolors
Defoliation & 2 & 432 & 216.0 & 2.54 & 0.11\\
Fruit\_thinning & 2 & 2669 & 1334.7 & 15.69 & 0.00\\
Replication & 2 & 405 & 202.7 & 2.38 & 0.12\\
Defoliation:Fruit\_thinning & 4 & 222 & 55.6 & 0.65 & 0.63\\
Residuals & 16 & 1361 & 85.0 &  & \\*
\end{longtable}

\rowcolors{2}{white}{white}\endgroup{}

\blandscape

\subsection{Treatment mean comparison}\label{treatment-mean-comparison}

\begingroup\fontsize{10}{12}\selectfont
\rowcolors{2}{white}{gray!6}

\begin{longtable}{>{\raggedright\arraybackslash}p{14em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}>{\raggedright\arraybackslash}p{1.8em}}
\caption{\label{tab:two-fac-groups-tab}Treatment means with groups}\\
\hiderowcolors
\toprule
\multicolumn{1}{c}{ } & \multicolumn{9}{c}{Fruit yield per plant kg} & \multicolumn{9}{c}{Fruit retention percent} \\
\cmidrule(l{2pt}r{2pt}){2-10} \cmidrule(l{2pt}r{2pt}){11-19}
Treatment & mean & group & std & r & Min & Max & Q25 & Q50 & Q75 & mean & group & std & r & Min & Max & Q25 & Q50 & Q75\\
\midrule
\endfirsthead
\caption[]{\label{tab:two-fac-groups-tab}Treatment means with groups \textit{(continued)}}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{9}{c}{Fruit yield per plant kg} & \multicolumn{9}{c}{Fruit retention percent} \\
\cmidrule(l{2pt}r{2pt}){2-10} \cmidrule(l{2pt}r{2pt}){11-19}
Treatment & mean & group & std & r & Min & Max & Q25 & Q50 & Q75 & mean & group & std & r & Min & Max & Q25 & Q50 & Q75\\
\midrule
\endhead
\
\endfoot
\bottomrule
\endlastfoot
\showrowcolors
Chemical thinning & 33.1 & b & 3.26 & 9 & 27.4 & 38.7 & 31.8 & 32.0 & 35.0 & 23.5 & b & 6.54 & 9 & 15.1 & 34.6 & 20.2 & 22.9 & 26.6\\
Hand thinning & 56.4 & a & 11.99 & 9 & 33.6 & 71.8 & 51.3 & 56.8 & 65.1 & 36.9 & a & 9.75 & 9 & 28.4 & 53.6 & 31.0 & 33.0 & 40.5\\
No thinning & 51.1 & a & 12.17 & 9 & 31.8 & 69.1 & 43.2 & 48.2 & 61.2 & 36.6 & a & 15.30 & 9 & 15.6 & 58.0 & 26.2 & 40.3 & 46.0\\
33\% defoliation & 48.6 & ab & 12.90 & 9 & 31.8 & 69.0 & 38.7 & 46.3 & 60.6 & 35.2 & a & 13.10 & 9 & 20.2 & 58.0 & 27.5 & 31.1 & 40.5\\
66\% defoliation & 50.7 & a & 15.78 & 9 & 31.4 & 71.8 & 36.3 & 48.2 & 65.1 & 31.7 & a & 12.86 & 9 & 15.1 & 53.6 & 23.6 & 28.4 & 40.3\\
\addlinespace
No defoliation & 41.4 & b & 12.91 & 9 & 27.4 & 66.2 & 32.0 & 33.9 & 51.3 & 30.0 & a & 12.26 & 9 & 15.1 & 52.1 & 22.9 & 28.4 & 34.6\\
Chemical thinning:33\% defoliation & 35.2 & cd & 3.44 & 3 & 31.8 & 38.7 & 33.4 & 35.0 & 36.8 & 24.5 & ab & 5.67 & 3 & 20.2 & 30.9 & 21.3 & 22.4 & 26.6\\
Chemical thinning:66\% defoliation & 33.2 & d & 2.70 & 3 & 31.4 & 36.3 & 31.6 & 31.8 & 34.0 & 21.8 & b & 5.94 & 3 & 15.1 & 26.6 & 19.4 & 23.6 & 25.1\\
Chemical thinning:No defoliation & 31.1 & d & 3.36 & 3 & 27.4 & 33.9 & 29.7 & 32.0 & 33.0 & 24.2 & ab & 9.85 & 3 & 15.1 & 34.6 & 19.0 & 22.9 & 28.8\\
Hand thinning:33\% defoliation & 58.6 & ab & 11.51 & 3 & 46.3 & 69.0 & 53.4 & 60.6 & 64.8 & 34.9 & ab & 4.99 & 3 & 31.1 & 40.5 & 32.1 & 33.0 & 36.8\\
\addlinespace
Hand thinning:66\% defoliation & 64.6 & a & 7.50 & 3 & 56.8 & 71.8 & 61.0 & 65.1 & 68.5 & 38.7 & ab & 13.22 & 3 & 28.4 & 53.6 & 31.2 & 33.9 & 43.8\\
Hand thinning:No defoliation & 45.9 & bcd & 10.64 & 3 & 33.6 & 52.8 & 42.5 & 51.3 & 52.0 & 37.2 & ab & 13.04 & 3 & 28.4 & 52.1 & 29.7 & 31.0 & 41.6\\
No thinning:33\% defoliation & 51.9 & abc & 9.14 & 3 & 42.9 & 61.2 & 47.2 & 51.5 & 56.3 & 46.3 & a & 16.48 & 3 & 27.5 & 58.0 & 40.5 & 53.5 & 55.8\\
No thinning:66\% defoliation & 54.5 & ab & 12.71 & 3 & 46.1 & 69.1 & 47.1 & 48.2 & 58.6 & 34.8 & ab & 14.71 & 3 & 18.1 & 46.0 & 29.2 & 40.3 & 43.1\\
No thinning:No defoliation & 47.1 & abcd & 17.48 & 3 & 31.8 & 66.2 & 37.5 & 43.2 & 54.7 & 28.6 & ab & 14.29 & 3 & 15.6 & 43.9 & 20.9 & 26.2 & 35.0\\*
\end{longtable}

\rowcolors{2}{white}{white}\endgroup{} \elandscape

\subsection{Effect of fruit thinning and defoliation on fruit
retention}\label{effect-of-fruit-thinning-and-defoliation-on-fruit-retention}

It was observed from the findings that, among the thinning treatments,
chemical thinning practice significantly decreased the percentage fruit
retention (Figure \ref{fig:treatments-fruit-retention}). Hand thinning
treatment exhibited higher fruit retention which was statistically at
par with no thinning treatment. With respect to defoliation practices,
there was no significant difference among treatments. But, the lowest
fruit retention was associated with 66 \% defoliation practice. These
results are in accordance with Zhou et al. (2000), Sharma, Singh and
Singh (2003) and Nartvaranant (2016), all of which report a higher
number of fruit set due to hand thinning treatment in papaya, peach and
pummelo, respectively. Zhou et al. (2000) reported that flower abortion
increased nine fold in `Sunset' papaya subjected to 75\% defoliation
which might be due to the lesser amount of photoassimilates being
available in the absence of source. (??Similarly, Jemric, Pavicic,
Blaskovic, Krapac, and Pavicic (2003) found that chemical thinning with
NAA caused lower crop density than hand thinned trees due to the strong
thinning property, epinasty effect on papaya (Subhadrabandhu, Thongplew,
\& Wasee, 1997) and toxic effects (Bhattarai, 2009) of NAA.??) Results
of flower and fruit drop are in contrast to that reported by Sharma
(2011) from the study on plum cv. Satluj Purple. He reported having
lowest fruit retention in control and the highest in NAA 60 ppm treated
plants followed by hand thinning, which might be due to a different
physiology of woody tree species and even, as reported by (??? cite),
due to an abberant behavior of higher plants/trees of having enhanced
fruit retaining tendency at lower concentration of NAA use.

\begin{figure}

{\centering \subfloat[Fruit thinning\label{fig:treatments-fruit-retention1}]{\includegraphics[width=.48\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/treatments-fruit-retention-1} }\subfloat[Defoliation\label{fig:treatments-fruit-retention2}]{\includegraphics[width=.48\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/treatments-fruit-retention-2} }\newline\subfloat[Fruit thinning x Defoliation\label{fig:treatments-fruit-retention3}]{\includegraphics[width=.48\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/treatments-fruit-retention-3} }

}

\caption{Effect of fruit thinning and defoliation on fruit retention of papaya (\textit{Carica papaya}) cv. Red Lady at Chitwan, Nepal, 2016}\label{fig:treatments-fruit-retention}
\end{figure}

\subsection{Effect of fruit thinning and defoliation on fruit
yield}\label{effect-of-fruit-thinning-and-defoliation-on-fruit-yield}

Significant difference was found in fruit yield due to fruit thinning
(Figure \ref{fig:treatments-fruit-yield}). The highest fruit yield (56.4
kg) was observed with hand thinning which is at par with control (51.1
kg). The lowest yield (33.2 kg) was found with chemical thinning. The
results obtained on yield are in harmony with the findings of Fischer et
al. (2011), who found highest increase in fruit yield due to hand
thinning over control treatment in apple which, might be due to
availability of photo-assimilates. Sharma et al. (2003) reported that
fruit yield was significantly higher in control as compared to chemical
thinning (NAA treated plants) might be due to the toxic effect of over
dose (Tahir \& Hamid, 2002; Bhattarai, 2009; Abbas, Ahmad \& Javaid,
2014). With regard to defoliation practices, there was no significant
difference in the yield between treatments. However, the highest yield
(50.7 kg) was recorded in 33\% defoliated plants
(\ref{tab:treatments-fruit-yield}). These results are supported by
Almanza-Merchan et al. (2011) who noticed higher exposure of the fruit
clusters to solar radiation stimulates the translocation of
photoassimilates towards the fruits and creates favorable
micro-environmental conditions.

\begin{figure}

{\centering \subfloat[Fruit thinning\label{fig:treatments-fruit-yield1}]{\includegraphics[width=.48\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/treatments-fruit-yield-1} }\subfloat[Defoliation\label{fig:treatments-fruit-yield2}]{\includegraphics[width=.48\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/treatments-fruit-yield-2} }\newline\subfloat[Fruit thinning x Defoliation\label{fig:treatments-fruit-yield3}]{\includegraphics[width=.48\linewidth]{analysis_and_interpretation_of_two_factor_files/figure-latex/treatments-fruit-yield-3} }

}

\caption{Effect of fruit thinning and defoliation on fruit yield of papaya (\textit{Carica papaya}) cv. Red Lady at Chitwan, Nepal, 2016}\label{fig:treatments-fruit-yield}
\end{figure}

\subsection{Effect of fruit thinning and defoliation on physical
characteristics of
papaya}\label{effect-of-fruit-thinning-and-defoliation-on-physical-characteristics-of-papaya}

Highly significant differences on fruit weight and fruit length of
papaya due to fruit thinning were noticed
(\ref{tab:two-fac-groups-tab}). The highest fruit weight (1631 g) and
fruit length (28.61 cm) was found with hand thinning. Lowest fruit
weight (999 g) and fruit length (24.01 cm) was with chemical thinning,
which was statistically at par with control thinning. Regarding the
defoliation treatments there was no significant difference between fruit
weight and fruit length. Fruit breadth was also found significantly
different among fruit thinning practices with highest (39.38 cm) in hand
thinning treatment. Among defoliation there was no significant
difference in fruit breadth.

The results of present study were consistent with Clingeleffer and
Petrie (2006) in grapes, Link (2000) in apple and Park et al. (2000) in
persimmon, who reported from the study on fruit thinning that higher
fruit weight was found at harvest. Similarly, Burge et al. (1987),
Sharma et al. (2003), and Nartvaranant (2016), reported that fruit
thinning increased size of fruit due to the more availability of
assimilates and higher leaf to fruit ratio.

Significant difference was observed in seed weight for different
thinning practices (\ref{tab:two-fac-groups-tab}); highest seed weight
(83.6 g) was observed with hand thinning and lowest seed weight was
found with chemical thinning (39.8 g) practice. Pathirana et al. (2015)
found in tomato that seed vigour and seed weight was higher due to fruit
thinning and canopy management than when left unattended. Lower seed
weight in fruit subjected to chemical thinning by NAA is probably due to
the parthenocarpic effect, which is supported by Nawaz et al. (2011),
albeit in mandarin. While, no significant difference was observed among
the defoliation treatment which might be due to the single defoliation
and recovery of vegetative growth by indeterminate growth habit of
papaya.

\subsection{Growth phenology of
papaya}\label{growth-phenology-of-papaya}

\subsubsection{Plant height (Ht)}\label{plant-height-ht}

\subsubsection{Number of leaves (NoL)}\label{number-of-leaves-nol}

\subsubsection{Stem diameter (SD)}\label{stem-diameter-sd}

\subsubsection{??? (PL)}\label{pl}

\subsubsection{Number of flowers ()}\label{number-of-flowers}

\subsubsection{Number of fruits set ()}\label{number-of-fruits-set}

\subsubsection{Other features \ldots{}}\label{other-features}

\section{Conclusion}\label{conclusion}

Chemical thinning increased flower and fruitlet abscission by 22 and 20
percent, respectively, than by hand thinning and without thinning
practices. While in 66\% defoliation abscission increased by 20 percent
than control treatment, fruit weight and seed weight were increased by
39 percent and 52 percent respectively, with hand thinning compared to
chemical thinning practice. While in no defoliation fruit weight
increased by 9 percent than 66\% defoliation practice. Hand thinning
practice increased 41 percent yield than chemical thinning while 33\%
defoliation increased 18 percent yield than 66\% defoliation. Chemical
thinning improved TSS and vitamin C content and hand thinning improved
shelf life of papaya. Hence, among the fruit thinning practices, hand
thinning was found as the most promising cultural practice and among
defoliation practices, 33\% defoliation showed the best yield and
quality of papaya.

\section{Acknowledgement}\label{acknowledgement}

Author are thankful to the Department of Horticulture and Directorate of
Research and Extension of Agriculture and Forestry University (AFU),
Rampur, Chitwan. We praise the experimental facility, including trial
plantation and the management, provided by Abloom Flora Farm, Chanauli,
Chitwan. Also highly acknowledged are: `Participatory Biodiversity and
Climate Change Assessment for Integrated Pest Management in the
Chitwan-Annapurna Landscape' project (USAID funded), who provided the
grant in cash and kind for this study.


\end{document}
